### PR TITLE
task updae

### PR DESCRIPTION
**Pull request by ANUSHAVAVILTHOTA**

### CODE REVIEW

**Comment by ANUSHAVAVILTHOTA** [comment]
.

**Comment by ANUSHAVAVILTHOTA** [comment]
task

**Comment by rajaathota72-fc** [comment]
Hey can you use functions and do it .

**Comment by ANUSHAVAVILTHOTA** [comment]
update speech to text.py

**Review by rajaathota72-fc — APPROVED** [review]

**Pull request merged**
